name: Check and Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Проверка наличия строки "Hello world"
        run: cat text1.txt text2.txt | grep -q 'Hello world'

  package:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Архивация файлов
        run: cat text1.txt text2.txt | gzip > packaged.gz
      - name: Загрузка артефакта
        uses: actions/upload-artifact@v4
        with:
          name: packaged
          path: packaged.gz
